
PLAY [Configure filesystem integrity using AIDE on RHEL8] **********************

TASK [Gathering Facts] *********************************************************
ok: [192.168.73.142]

TASK [Install AIDE package] ****************************************************
changed: [192.168.73.142]

TASK [Copy AIDE configuration file] ********************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: If you are using a module and expect the file to exist on the remote, see the remote_src option
fatal: [192.168.73.142]: FAILED! => changed=false 
  msg: |-
    Could not find or access 'files/aide.conf'
    Searched in:
            /home/mario/Documents/codigo-BOT-definitivo/ansibleGPT-UseCases-tests/case7/low/files/files/aide.conf
            /home/mario/Documents/codigo-BOT-definitivo/ansibleGPT-UseCases-tests/case7/low/files/aide.conf
            /home/mario/Documents/codigo-BOT-definitivo/ansibleGPT-UseCases-tests/case7/low/files/files/aide.conf
            /home/mario/Documents/codigo-BOT-definitivo/ansibleGPT-UseCases-tests/case7/low/files/aide.conf on the Ansible Controller.
    If you are using a module and expect the file to exist on the remote, see the remote_src option
...ignoring

TASK [Add cron job for AIDE check] *********************************************
changed: [192.168.73.142]

PLAY RECAP *********************************************************************
192.168.73.142             : ok=4    changed=2    unreachable=0    failed=0    skipped=0    rescued=0    ignored=1   

Playbook run took 0 days, 0 hours, 1 minutes, 7 seconds
